return { -- Autoformat
  "stevearc/conform.nvim",
  opts = {
    notify_on_error = true,
    format_on_save = {
      lsp_fallback = true,
      timeout_ms = 2000,
    },
    formatters_by_ft = {
      lua = { "stylua" },
      python = { "autopep8" },
      javascript = { "prettier", stop_after_first = true },
      typescript = { "prettier", stop_after_first = true },
      javascriptreact = { "prettier", stop_after_first = true },
      typescriptreact = { "prettier", stop_after_first = true },
      css = { "prettier" },
      html = { "prettier" },
      yaml = { "prettier" },
      json = { "prettier" },
      graphql = { "prettier" },
      ruby = { "rubyfmt" },
      rust = { "rustfmt" },
      sql = { "sqlfmt" },
      sh = { "shfmt" },
      go = { "gofmt" },
      zig = { "zigfmt" },
      c = { "clang_format" },
      cpp = { "clang_format" },
    },
  },
}
